variable "vpc_cidr_block" {}
variable "vpc_name" {}
variable "pub_sub_1" {}
variable "az_1" {}
variable "pub_sub_1_cidr" {}
variable "pub_sub_2_cidr" {}
variable "az_2" {}
variable "pub_sub_2" {}
variable "prvt_sub_1" {}
variable "prvt_sub_1_cidr" {}
variable "prvt_sub_2_cidr" {}
variable "prvt_sub_2" {}
variable "IGW" {}
variable "eip_name" {}
variable "NAT" {}
variable "all_cidr" {}
variable "PubRT" {}
variable "PrvtRT" {}

