variable "profilename" {}
variable "region" {}
variable "vault_domain" {}
variable "token" {}
variable "projectname" {}
variable "identifier" {}
variable "vpc_cidr" {}
variable "pub_sub_1_cidr" {}
variable "pub_sub_2_cidr" {}
variable "prvt_sub_1_cidr" {}
variable "prvt_sub_2_cidr" {}
variable "all_cidr" {}
variable "az_1" {}
variable "az_2" {}
variable "ami_redhat" {}
variable "instance_type2" {}
variable "project_name" {}
variable "newrelic_license_key" {}
variable "acct_id" {}
variable "domain_name" {}
variable "domain_name2" {}
variable "domain_name3" {}
variable "domain_name4" {}
variable "ami_ubuntu" {}
variable "env" {}
variable "env1" {}