variable "profilename" {}
variable "region" {}
variable "vault_domain" {}
variable "token" {}
variable "projectname" {}
variable "identifier" {}
variable "vpc_cidr" {}
variable "pub_sub_1_cidr" {}
variable "pub_sub_2_cidr" {}
variable "prvt_sub_1_cidr" {}
variable "prvt_sub_2_cidr" {}
variable "all_cidr" {}
variable "az_1" {}
variable "az_2" {}
