---
  - hosts: webservers
    become: true
    vars_files:
      - ansible_vars_file.yml
    tasks:
      - name: Stopping Running Container
        command: docker stop appContainer
        ignore_errors: yes
      - name: Removing stopped container
        command: docker rm appContainer
        ignore_errors: yes
      - name: Removing docker image
        command: docker rmi \"{{ NEXUS_IP }}\"/myapp:latest
        ignore_errors: yes
      - name: Pulling docker image from nexus and creating container
        shell: |
          sudo su -c \"docker login --username=admin --password=admin123 {{ NEXUS_IP }}\" ec2-user
          sudo su -c \"docker pull \"{{ NEXUS_IP }}\"/myapp:latest\" ec2-user
          sudo su -c \"docker run -it -d --name appContainer -p 8080:8080 \"{{ NEXUS_IP }}\"/myapp:latest\" ec2-user