variable "ami_redhat" {}
variable "subnet_id" {}
variable "ansible_SG" {}
variable "keypair_name" {}
variable "ansible_name" {}
variable "staging_playbook" {}
variable "prod_playbook" {}
variable "staging_discovery_script" {}
variable "prod_discovery_script" {}
variable "keypair" {}
variable "nexus_ip" {}
variable "newrelic_license_key" {}
variable "acct_id" {}