variable "stage_lt_name" {}
variable "instance_type" {}
variable "lt_sg" {}
variable "key_name" {}
variable "nexus_ip" {}
variable "newrelic_license_key" {}
variable "acct_id" {}
variable "ami_id" {}
variable "stage_asg_name" {}
variable "vpc_zone_identifier" {}
variable "stage_tg_arn" {}
variable "stage_asg_policy_type" {}
variable "prod_lt_name" {}
variable "prod_asg_name" {}
variable "prod_tg_arn" {}
variable "prod_asg_policy_type" {}